### Multiple Linear Regression

###### Temel amaç, bağımlı ve bağımsız değişkenler arasındaki ilişkiyi ifade eden doğrusal fonksiyonu bulmaktır.

###### Hatalar normal dağılır.
###### Hatalar birbirinden bağımsızdır ve aralarında otokorelasyon yoktur.
###### Her bir gözlem için hata terimleri varyansları sabittir.
###### Değişkenler ile hata terimi arasında ilişki yoktur.
###### Bağımsız değişkenler arasında çoklu doğrusal ilişki problemi yoktur.

In [1]:
import pandas as pd
df = pd.read_csv("Advertising.csv")
df = df.iloc[:,1:len(df)]
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop('sales', axis=1)
y = df[["sales"]]

##### Statsmodels

In [5]:
import statsmodels.api as sm

In [6]:
lm = sm.OLS(y, X)

In [7]:
model = lm.fit()

In [8]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Fri, 23 Dec 2022   Prob (F-statistic):                   2.43e-171
Time:                        16:13:38   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

###### R-squared: Bağımsız değişkenlerin, bağımlı değişkendeki değişikliği açıklama yüzdesi
###### Adj. R-squared: R-karenin düzeltilmiş hali (Açıklama oranı/yüzdesi)
###### F-statistic: Modelin anlamlılığını test etmek için kullanılır
###### Prob(F-statistic): F istatistiğine ilişkin P-Value değeri ( < 0.05 ise anlamlı)
###### coef: Bağımsız değişkenlerin katsayısı(B1, B2, B3)
###### std err: Standart hata
###### t: Standart hatanın anlamlılığını ölçer
###### P>|t|: P-Value değeri ( < 0.05 ise anlamlı)

#### Scikit Learn

In [9]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()

In [10]:
model = lm.fit(X, y)

In [12]:
# B0 sabiti
model.intercept_

array([2.93888937])

In [13]:
# B1 katsayısı
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

#### Predict
###### Sales = 2.94 + TV * 0.04 + radio * 0.19 - newspaper * 0.001

###### 30 birim TV, 10 birim radio, 40 birim gazete harcamaları

In [14]:
2.94  + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [17]:
new_data = [[30],[10],[40]]

In [19]:
import pandas as pd
new_data = pd.DataFrame(new_data).T

In [21]:
new_data.columns = ["TV", "radio", "newspaper"]
new_data

TV  radio  newspaper
0  30     10         40

In [22]:
model.predict(new_data)

array([[6.15562918]])

In [23]:
from sklearn.metrics import mean_squared_error

In [26]:
# Hata kareleri ortalaması (gerçek değerler, tahmin edilen değerler)
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [27]:
# Hata kareleri ortalamasının karekökü
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

#### Model Tuning (Model Doğrulama)

##### MLR'de bir hiperparametre olmadığından dolayı model doğrulama işlemi gerçekleştirilir. (Sınama seti yaklaşımı ve K-katlı çapraz doğrulama yaklaşımı)

In [28]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [29]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [30]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

In [43]:
X_train.head()

TV  radio  newspaper
108   13.1    0.4       25.6
107   90.4    0.3       23.2
189   18.7   12.1       23.4
14   204.1   32.9       46.0
56     7.3   28.1       41.4

In [44]:
y_train.head()

sales
108    5.3
107    8.7
189    6.7
14    19.0
56     5.5

In [45]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [46]:
# Train error
np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.736902590147092

In [47]:
# Test error
np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4113417558581587

In [48]:
# K_fold Cross Validation
from sklearn.model_selection import cross_val_score

In [49]:
cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")

array([-1.62375953, -3.81875608, -3.43828142, -2.27748673, -7.25325414,
       -1.88303708, -2.80517715, -3.68594486, -1.12810834, -3.96330989])

###### Train seti üzerinden 10 adet farklı hata hesaplandı. Yani train seti 10 parçaya bölündü. 9 parçayla model kuruldu ve dışarıda kalan 1 parça tahmin edildi. Bu işlemle 10 farklı hata elde edildi.

In [52]:
# CV ile elde edilmiş MSE(Ortalama hata)
np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error"))

3.187711520944357

In [55]:
# CV ile elde edilmiş RMSE
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")))

1.7854163438661463

In [57]:
np.sqrt(np.mean(-cross_val_score(model, X, y, cv=10, scoring="neg_mean_squared_error")))

1.749276312684338